### ISSUE TITLE
計算回数が増加してしまうため、値を定義してしまってもいいのではないでしょうか?

### ISSUE THREAD

**Issue by kotaokuda** [c0a2108119/ProjExD#10]
https://github.com/c0a2108119/ProjExD/blob/c3f10b54097e87ec40ed0763769c80e65f8ec926/ex03/maze.py#L78

**Comment by c0a2108119** [comment]
ここでは、スタート地点が一番左上の床に来るようにし、スタート地点から始められるようにするために計算しています。maze[1][1]に壁が来ないかどうかわからなかったので(おそらく来ないと思うが念のため)、計算してスタート地点を設定しています。
