### ISSUE TITLE
空白

### ISSUE THREAD

**Issue by nisiyama158** [c0a2108119/ProjExD#15]
https://github.com/c0a2108119/ProjExD/blob/6a1aadc2cc47a92b9b4d4f44edebff8be926086d/ex05/dodge_bomb.py#L81
こんなに空けなくても良い気がします

**Comment by c0a2108119** [comment]
ご覧のスクリプトは3限のdodge_bomb.pyですが、あっていますか？
このスクリプトは提出するものではないので、更新しておらず最新の状態ではないです

**Comment by nisiyama158** [comment]
失礼しました。更新前のものを見ていたようです。
