### ISSUE TITLE
素人質問で恐縮ですが

### ISSUE THREAD

**Issue by c0a21029** [c0a2108119/ProjExD#5]
https://github.com/c0a2108119/ProjExD/blob/9a80a1a5ec950da5cccc3727057e11ef9e921628/ex02/calc.py#L18
ここにこの分岐を記述するなら、15行目あたりの同様の記述は抜けないのでしょうか。

**Comment by c0a2108119** [comment]
シンプルにこの分岐を抜くだけだと意図しない挙動になるため、分岐の位置をわかりやすい(自社比)位置に変更してみました。この分岐は演算子を続けて入力しないようにするものであるため、すでにmarkがfalseであるときもTrueであるときも分岐する必要があると思います。
