### ISSUE TITLE
Returnの返り値が指定されてませんが、Noneでは?

### ISSUE THREAD

**Issue by kotaokuda** [c0a2108119/ProjExD#7]
https://github.com/c0a2108119/ProjExD/blob/9a80a1a5ec950da5cccc3727057e11ef9e921628/ex02/calc.py#L50

**Comment by c0a2108119** [comment]
""をリターンするかNoneをリターンするかの違いなので動きはしますが、入れるつもりで入れ忘れていたので修正しました。ありがとうございます。
