### ISSUE TITLE
非常に良いコード

### ISSUE THREAD

**Issue by nisiyama158** [c0a2108119/ProjExD#8]
https://github.com/c0a2108119/ProjExD/blob/c3f10b54097e87ec40ed0763769c80e65f8ec926/ex03/maze.py#L38

良いコードだと思います。指摘する箇所があまりにもないのでほぼいちゃもんみたいになってしまうのですが、元ある画像群を五倍にすると画質の荒さが目立つので、いっその事別の画像に置き換えることをおすすめします。適用させる画像は同じ画像をAI補完するとかで。

**Comment by c0a2108119** [comment]
ありがとうございます。ご指摘の点ですが、大きな画像を用意するのが困難なこと、この程度の粗さであれば個人的に嫌いじゃないレベルであること、の二点を理由にそのままにさせてほしいです。
